export const colorPrimitives = {
  black: 'var(--ref-color-black)',
  white: 'var(--ref-color-white)',
  gray: {
    100: 'var(--ref-color-gray-100)',
    90: 'var(--ref-color-gray-90)',
    80: 'var(--ref-color-gray-80)',
    70: 'var(--ref-color-gray-70)',
    60: 'var(--ref-color-gray-60)',
    50: 'var(--ref-color-gray-50)',
    40: 'var(--ref-color-gray-40)',
    30: 'var(--ref-color-gray-30)',
    20: 'var(--ref-color-gray-20)',
    10: 'var(--ref-color-gray-10)',
  },
  blue: {
    100: 'var(--ref-color-blue-100)',
    90: 'var(--ref-color-blue-90)',
    80: 'var(--ref-color-blue-80)',
    70: 'var(--ref-color-blue-70)',
    60: 'var(--ref-color-blue-60)',
    50: 'var(--ref-color-blue-50)',
    40: 'var(--ref-color-blue-40)',
    30: 'var(--ref-color-blue-30)',
    20: 'var(--ref-color-blue-20)',
    10: 'var(--ref-color-blue-10)',
  },
  cyan: {
    100: 'var(--ref-color-cyan-100)',
    90: 'var(--ref-color-cyan-90)',
    80: 'var(--ref-color-cyan-80)',
    70: 'var(--ref-color-cyan-70)',
    60: 'var(--ref-color-cyan-60)',
    50: 'var(--ref-color-cyan-50)',
    40: 'var(--ref-color-cyan-40)',
    30: 'var(--ref-color-cyan-30)',
    20: 'var(--ref-color-cyan-20)',
    10: 'var(--ref-color-cyan-10)',
  },
  teal: {
    100: 'var(--ref-color-teal-100)',
    90: 'var(--ref-color-teal-90)',
    80: 'var(--ref-color-teal-80)',
    70: 'var(--ref-color-teal-70)',
    60: 'var(--ref-color-teal-60)',
    50: 'var(--ref-color-teal-50)',
    40: 'var(--ref-color-teal-40)',
    30: 'var(--ref-color-teal-30)',
    20: 'var(--ref-color-teal-20)',
    10: 'var(--ref-color-teal-10)',
  },
  green: {
    100: 'var(--ref-color-green-100)',
    90: 'var(--ref-color-green-90)',
    80: 'var(--ref-color-green-80)',
    70: 'var(--ref-color-green-70)',
    60: 'var(--ref-color-green-60)',
    50: 'var(--ref-color-green-50)',
    40: 'var(--ref-color-green-40)',
    30: 'var(--ref-color-green-30)',
    20: 'var(--ref-color-green-20)',
    10: 'var(--ref-color-green-10)',
  },
  yellow: {
    100: 'var(--ref-color-yellow-100)',
    90: 'var(--ref-color-yellow-90)',
    80: 'var(--ref-color-yellow-80)',
    70: 'var(--ref-color-yellow-70)',
    60: 'var(--ref-color-yellow-60)',
    50: 'var(--ref-color-yellow-50)',
    40: 'var(--ref-color-yellow-40)',
    30: 'var(--ref-color-yellow-30)',
    20: 'var(--ref-color-yellow-20)',
    10: 'var(--ref-color-yellow-10)',
  },
  orange: {
    100: 'var(--ref-color-orange-100)',
    90: 'var(--ref-color-orange-90)',
    80: 'var(--ref-color-orange-80)',
    70: 'var(--ref-color-orange-70)',
    60: 'var(--ref-color-orange-60)',
    50: 'var(--ref-color-orange-50)',
    40: 'var(--ref-color-orange-40)',
    30: 'var(--ref-color-orange-30)',
    20: 'var(--ref-color-orange-20)',
    10: 'var(--ref-color-orange-10)',
  },
  red: {
    100: 'var(--ref-color-red-100)',
    90: 'var(--ref-color-red-90)',
    80: 'var(--ref-color-red-80)',
    70: 'var(--ref-color-red-70)',
    60: 'var(--ref-color-red-60)',
    50: 'var(--ref-color-red-50)',
    40: 'var(--ref-color-red-40)',
    30: 'var(--ref-color-red-30)',
    20: 'var(--ref-color-red-20)',
    10: 'var(--ref-color-red-10)',
  },
  magenta: {
    100: 'var(--ref-color-magenta-100)',
    90: 'var(--ref-color-magenta-90)',
    80: 'var(--ref-color-magenta-80)',
    70: 'var(--ref-color-magenta-70)',
    60: 'var(--ref-color-magenta-60)',
    50: 'var(--ref-color-magenta-50)',
    40: 'var(--ref-color-magenta-40)',
    30: 'var(--ref-color-magenta-30)',
    20: 'var(--ref-color-magenta-20)',
    10: 'var(--ref-color-magenta-10)',
  },
  violet: {
    100: 'var(--ref-color-violet-100)',
    90: 'var(--ref-color-violet-90)',
    80: 'var(--ref-color-violet-80)',
    70: 'var(--ref-color-violet-70)',
    60: 'var(--ref-color-violet-60)',
    50: 'var(--ref-color-violet-50)',
    40: 'var(--ref-color-violet-40)',
    30: 'var(--ref-color-violet-30)',
    20: 'var(--ref-color-violet-20)',
    10: 'var(--ref-color-violet-10)',
  },
} as const;

export const colors = {
  primary: 'var(--color-primary)',
  onPrimary: 'var(--color-on-primary)',
  primaryContainer: 'var(--color-primary-container)',
  onPrimaryContainer: 'var(--color-on-primary-container)',

  secondary: 'var(--color-secondary)',
  onSecondary: 'var(--color-on-secondary)',
  secondaryContainer: 'var(--color-secondary-container)',
  onSecondaryContainer: 'var(--color-on-secondary-container)',

  tertiary: 'var(--color-tertiary)',
  onTertiary: 'var(--color-on-tertiary)',
  tertiaryContainer: 'var(--color-tertiary-container)',
  onTertiaryContainer: 'var(--color-on-tertiary-container)',

  background: 'var(--color-background)',
  onBackground: 'var(--color-on-background)',
  surface: 'var(--color-surface)',
  onSurface: 'var(--color-on-surface)',
  surfaceVariant: 'var(--color-surface-variant)',
  onSurfaceVariant: 'var(--color-on-surface-variant)',

  inverseSurface: 'var(--color-inverse-surface)',
  inverseOnSurface: 'var(--color-inverse-on-surface)',
  inversePrimary: 'var(--color-inverse-primary)',

  outline: 'var(--color-outline)',
  outlineVariant: 'var(--color-outline-variant)',
  scrim: 'var(--color-scrim)',

  layer1: 'var(--color-layer-1)',
  layer2: 'var(--color-layer-2)',
  layer3: 'var(--color-layer-3)',
  onLayer: 'var(--color-on-layer)',

  positive: 'var(--color-positive)',
  onPositive: 'var(--color-on-positive)',
  positiveContainer: 'var(--color-positive-container)',
  onPositiveContainer: 'var(--color-on-positive-container)',

  positiveLegacy: 'var(--color-positive-legacy)',
  onPositiveLegacy: 'var(--color-on-positive-legacy)',
  positiveLegacyContainer: 'var(--color-positive-legacy-container)',
  onPositiveLegacyContainer: 'var(--color-on-positive-legacy-container)',

  negative: 'var(--color-negative)',
  onNegative: 'var(--color-on-negative)',
  negativeContainer: 'var(--color-negative-container)',
  onNegativeContainer: 'var(--color-on-negative-container)',

  cautionary: 'var(--color-cautionary)',
  onCautionary: 'var(--color-on-cautionary)',
  cautionaryContainer: 'var(--color-cautionary-container)',
  onCautionaryContainer: 'var(--color-on-cautionary-container)',

  neutral: 'var(--color-neutral)',
  onNeutral: 'var(--color-on-neutral)',
  neutralContainer: 'var(--color-neutral-container)',
  onNeutralContainer: 'var(--color-on-neutral-container)',

  actionPrimaryBg: 'var(--color-action-primary-bg)',
  actionPrimaryText: 'var(--color-action-primary-text)',
  actionPrimaryInverseBg: 'var(--color-action-primary-inverse-bg)',
  actionPrimaryInverseText: 'var(--color-action-primary-inverse-text)',

  actionSecondaryBg: 'var(--color-action-secondary-bg)',
  actionSecondaryText: 'var(--color-action-secondary-text)',
  actionSecondaryStroke: 'var(--color-action-secondary-stroke)',
  actionSecondaryInverseText: 'var(--color-action-secondary-inverse-text)',
  actionSecondaryInverseStroke: 'var(--color-action-secondary-inverse-stroke)',
} as const;

export type ColorPrimitivePalette = keyof typeof colorPrimitives;
export type ColorToken = keyof typeof colors;
